countries = ['Germany', 'America', 'Georgia', 'Great Britain', 'France', 'Switczerland']
print(countries)
print(sorted(countries))
print(countries)
print(sorted(countries, reverse = True))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse = True)
print(countries)

print('\nNumber of countries in list: ' + str(len(countries)))